Mvc5_Contatos/Models/ContatoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mvc5_Contatos.Models
{
    public class ContatoViewModel
    {
        public int ContatoId { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public virtual EnderecoViewModel Endereco { get; set; }
        public virtual int EnderecoId { get; set; }
    }
}

Mvc5_Contatos/Controllers/ContatosController.cs
using Mvc5_Contatos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using PagedList;


namespace Mvc5_Contatos.Controllers
{
    public class ContatosController : Controller
    {
        //Lista os contatos sem o endereço
        // GET: Contatos
        public ActionResult Index(int? pagina)
        {
            int paginaTamanho = 4;
            int paginaNumero = (pagina ?? 1);
            IEnumerable<ContatoViewModel> contatos = null;

            using(var client = new HttpClient())
            {
                
                client.BaseAddress = new Uri("http://localhost:59216/api/");

                //HTTP GET
                var responseTask = client.GetAsync("contatos");
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<ContatoViewModel>>();
                    readTask.Wait();

                    contatos = readTask.Result;
                }
                else
                {
                    contatos = Enumerable.Empty<ContatoViewModel>();
                    ModelState.AddModelError(string.Empty, "Erro no servidor.Contate o Administrador.");
                }
            return View(contatos.ToPagedList(paginaNumero, paginaTamanho));
            }
           
        }

        //Criar um novo contato
        [HttpGet]
        public ActionResult create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult create(ContatoEnderecoViewModel contato)
        {
            if(contato == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<ContatoEnderecoViewModel>("contatos", contato);
                postTask.Wait();
                var result = postTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, "Erro no Servidor. Contate o Administrador.");
                return View(contato);
            }
        }

        //Editar um contato
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContatoViewModel contato = null;
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/contatos");

                //HTTP GET
                var responseTask = client.GetAsync("?id=" + id.ToString());
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ContatoViewModel>();
                    readTask.Wait();

                    contato = readTask.Result;
                }
            }
            return View(contato);
        }

        [HttpPost]
        public ActionResult Edit(ContatoViewModel contato)
        {
            if(contato == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/");

                //HTTP PUT
                var putTask = client.PutAsJsonAsync<ContatoViewModel>("contatos", contato);
                putTask.Wait();
                var result = putTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(contato);
        }

        //Deletar um contato
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ContatoViewModel contato = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("contatos/" + id.ToString());
                deleteTask.Wait();
                var result = deleteTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(contato);
        }

        //Detales de um contato
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ContatoViewModel contato = null;

            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/contatos");

                //HTTP GET
                var responseTask = client.GetAsync("?id=" + id.ToString());
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ContatoViewModel>();
                    readTask.Wait();

                    contato = readTask.Result;
                }
            }
            return View(contato);
        }

        //SEARCH - BUSCAR UM CONTATO PELO NOME

        public ActionResult Search(string nome)
        {
            IEnumerable<ContatoViewModel> contatos = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59216/api/");

                //HTTP GET
                var responseTask = client.GetAsync("contatos?nome=" + nome);
                responseTask.Wait();
                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<ContatoViewModel>>();
                    readTask.Wait();

                    contatos = readTask.Result;
                }
                else
                {
                    contatos = Enumerable.Empty<ContatoViewModel>();
                    ModelState.AddModelError(string.Empty, "Erro no servidor.Contate o Administrador.");
                }
                return View(contatos);
            }
        }
    }
}

Mvc5_Contatos/Views/Contatos/Details.cshtml
@model Mvc5_Contatos.Models.ContatoViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Detales do Contato</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContatoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContatoId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Local)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Local)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Cidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Endereco.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco.Estado)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ContatoId}) |
    @Html.ActionLink("Retornar", "Index")
</p>

Mvc5_Contatos/Views/Contatos/Edit.cshtml
@model Mvc5_Contatos.Models.ContatoViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar dados do Contato</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @*<h4>ContatoViewModel</h4>*@
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ContatoId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContatoId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContatoId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Local, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Local, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Local, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Cidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Cidade, "", new { @class = "text-danger" })
        </div>
    </div> 
    <div class="form-group">
        @Html.LabelFor(model => model.Endereco.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Endereco.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar aterações" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retornar", "Index")
</div>

Mvc5_Contatos/Views/Contatos/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<Mvc5_Contatos.Models.ContatoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Relação de Contatos</h2>

@using(Html.BeginForm("Search", "Contatos", FormMethod.Get))
     {
        @Html.Label("Nome", "Nome")
       <input type="text" name="nome"/>
       <input type="submit" name="submit" value="Procurar"/>
      }

<p>
    @Html.ActionLink("Criar Novo Contato", "Create")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.ContatoId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model[0].Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Telefone)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.EnderecoId)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.ContatoId)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.EnderecoId)
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContatoId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ContatoId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ContatoId },
                new { onclick = "return confirm('Desseja realmente deletar este contato ?');" })
            </td>
        </tr>
    }
    <tr>
        <td>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </td>
    </tr>

</table>

<div>
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

    @if (Model.HasPreviousPage)
            {
        @Html.ActionLink("<", "Index", new { pagina = 1 })
        @Html.Raw(" ");
        @Html.ActionLink("[ Anterior", "Index", new {pagina = Model.PageNumber - 1})
            }
            else
            {
                @:<
                @Html.Raw(" ");
                @:< Anterior
            }
    @if (Model.HasNextPage)
            {
                @Html.ActionLink("Próxima ]", "Index", new { pagina = Model.PageNumber + 1})
                @Html.Raw(" ");
                @Html.ActionLink(">", "Index", new { pagina = Model.PageCount})
            }
            else
            {
                @:Próxima >
                @Html.Raw(" ")
                @:>
            }       
</div>

Mvc5_Contatos/Views/Contatos/Search.cshtml
@model IEnumerable<Mvc5_Contatos.Models.ContatoViewModel>

@{
    ViewBag.Title = "Search";
}

<h2>Relação de Contatos</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.ContatoId)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.EnderecoId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ContatoId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.EnderecoId)
                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContatoId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ContatoId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ContatoId },
               new { onclick = "return confirm('Deseja realmente deletar este contato ?');" })
            </td>
        </tr>
    }
    <tr>
        <td>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </td>
    </tr>

</table>

Mvc5_Contatos/Views/Contatos/create.cshtml
@model Mvc5_Contatos.Models.ContatoEnderecoViewModel

@{
    ViewBag.Title = "create";
}

<h2>Criar um Novo Contato</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>ContatoEnderecoViewModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.ContatoId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContatoId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContatoId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Local, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar Contato" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}